language: node_js
node_js:
  - "10"
  - "12"

env:
  - CXX=g++-4.8

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  postgresql: "9.4"

services:
  - mysql
